### ISSUE TITLE
일일 방문자 수 처리 최적화 문제

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/random#9]
### 문제 상황

모든 유저들의 각 블로그 방문자 수를 DB에서 관리하는데
매일 자정마다 방문자 수를 0으로 초기화한다
유저가 10억 명이라서 10억 개의 row를 일괄 update하면서 병목 현상이 발생하는데
이를 해결할 수 있는 방법은?

![image](https://user-images.githubusercontent.com/19742896/149653165-3bfbb820-6d80-4622-a44f-b401f8c534ab.png)

### 관련 챕터
https://github.com/caffeine-library/system-design-interview/issues/1#issue-1088760051
(캐시 서버, Redis)

---
@caffeine-library/readers-system-design-interview

**Comment by JasonYoo1995** [comment]
### Redis를 사용하는 방법

먼저 레디스를 DB에 대한 캐시 서버로 사용합니다
즉 레디스에서 방문자 수가 관리됩니다
평소에는 레디스의 데이터를 1초 간격으로 DB에 반영합니다
0시에는 일괄적으로 DB 방문자 수 컬럼을 초기화합니다
모든 튜플을 초기화하는 데에 10초가 걸린다고 가정하면
그 10초 동안은 실시간으로 들어오는 방문자 수들을 레디스에서 관리를 하고
레디스의 데이터를 DB에 반영하는 것을 일시 중지합니다
즉, 오직 레디스에서만 방문자 수를 처리합니다
10초 뒤 DB 초기화가 끝나면 그 때부터 다시 1초 간격으로 레디스의 데이터를 DB에 반영합니다
또한 추가적으로 vertical partitioning을 이용해 방문자 수 컬럼만 따로 다른 테이블로 분리하면 좀 더 병목현상이 완화되어 높은 사용자 경험을 만들어낼 수 있을 것 같습니다

### index를 사용하는 방법
index는 read에 대한 빠른 접근 경로를 만듦으로써
기본적으로 write 속도를 희생하고 read 속도를 최적화하는 것인데
index를 이용해 write 속도를 최적화하는 건 불가능해 보입니다

### lazy하게 update하는 방법
반드시 정확히 자정에 DB 모든 tuple이 0으로 초기화될 필요는 없습니다.
임의의 사용자가 어떤 날에 어떤 블로그를 최초로 방문하는 시점에, 그 블로그에 해당하는 row 하나만 초기화하면 됩니다.
**\<update query>**
update timestamp가 오늘 날짜가 아니면 1으로 set
update timestamp가 오늘 날짜이면 cnt++
**\<select query>**
update timestamp가 오늘 날짜가 아니면 0
update timestamp가 오늘 날짜이면 그대로 read

@caffeine-library/readers-system-design-interview

**Comment by binchoo** [comment]
"블로그 조회수 초기화"를 튜플 업데이트로 구현하는 방식에서 탈피
- 방문자 테이블
  | pk            | blog_id                  | visitor_id               | date     |
  | ------------- | ------------------------ | ------------------------ | -------- |
  | 프라이머리 키 | 블로그를 나타내는 외래키 | 방문자를 나타내는 외래키 | 방문일자 |

- 블로그 조회수를 변경하기 위해 기존 튜플을 수정하는 행위
  - '조회수' 라는 속성이 블로그라는 엔터티에 종속되어야 하는 속성인지 의문이다.
- 조회수는 블로그 관련 통계 메트릭의 하나이며 방문자 분석 기능과 연계될 수 있다. 따라서 위와 같은 테이블 구조를 제안함.
- 조회수의 증가는 방문자 테이블에 튜플을 추가하는 것으로 달성된다.
- 조회수의 초기화는, 방문자 테이블에 오늘 날짜를 갖는 튜플이 없는데에서 알아서 구현된다.
- 당일 블로그 A의 조회수는 다음 쿼리로 얻을 수 있다.
  - `select count(*) from 방문자 테이블 where date=오늘 and blog_id=A`
